### ISSUE TITLE
Clarify definition -Original Version

### ISSUE THREAD

**Issue by jack-watts** [imfug/002-pkg-and-delivery#19]
The term 'Original Version' presents varying connotations across the industry depending if one is management or manufacturing. The WG determined that it best to describe the term explicitly stating the context(s) in which it is used.

Brian H. to create the first draft.

**Comment by Insanitygift** [comment]
Original Version (OV) Definition  (Brian Vessa)

The Original Version (OV) is the original complete work as conceived, created and produced by the talent. Any variances in the picture (e.g. aspect ratio), edit, language or text means it is no longer the original version.

From the standpoint of IMF or DCP, there is only one unique composition that is the original version. The components of this composition, such as picture, audio, text and subtitle files, may be located in one or more packages using any number of tracks.

**Comment by palemieux** [comment]
@Insanitygift The definition of Original Version above ties Original Version to a specific Composition. This seems to conflict with the definition of Original Version in [EIDR](http://eidr.org/documents/EIDR_2.0_Data_Fields.pdf) which is associated with an Edit and not a specific manifestation.

**Comment by Insanitygift** [comment]
There is the original edit of the movie, yes. But that alone does not constitute the "original version" as it is known in the vernacular. There are other components that must be present in their original state to constitute "original version". I wanted to define how its known in the vernacular, as that is how content providers reference it.

**Comment by palemieux** [comment]
A Composition refers to a specific Composition Playlist with a specific UUID.

I am skeptical that folks refer to a specific Composition Playlist when they refer to the Original Version, since it would mean that the exact Composition Playlist and assets would need to be archived as-is forever.

**Comment by Insanitygift** [comment]
Actually, we had this discussion, not sure if you were at that meeting, but there is a distinction between composition and CPL, and we even removed "CPL" from various places in the text. This is why I said "The components of this composition, such as picture, audio, text and subtitle files, may be located in one or more packages using any number of tracks." It is possible to have IMF's created in different ways with different track contents and a number of other variables, and for each of these to actually play out the same composition they will require different CPL's. As a quick example, one could author an IMF so that the logos were in a track file, the main movie picture was in a track file, and the credits were in a track file. To play the original version will require CPL#1 that references these three track files. But I could also have an IMF that has all of these in one track file. So to play the original version will require CPL#2, which references one track file. The resultant playout is the same composition, but done with different CPL's because of the nature of how the tracks are created. So it's not the CPL that is unique, it is the composition. So I agree, folks don't refer to a particular CPL when referring to Original Version, they are referring to the composition itself. Perhaps we need to expand the definition of composition in IMF, or, find a term that means "what it is composed of" that is not specific to exact track files and UUID's. The Original Version is extremely specific in what it is composed of, but how you get there (IMF tracks, packages and CPL's) can vary depending on how the authoring is done. That's why I think it's best to call the OV a unique composition and say nothing of CPL's.

**Comment by palemieux** [comment]
> for each of these to actually play out the same composition they will require different CPL's.

ST 2026-2 specifies that a Composition refers to a single CPL:

_A Composition consists of one Composition Playlist, as specified in SMPTE ST 2067-3, and all Assets, e.g Track Files, it references._

I think you mean _Generic Manifestation_ (or perhaps _Edit_) instead of _IMF Composition_.

See the diagram at Section 2 of https://eidr.org/documents/Using_EIDR_with_IMF.pdf

**Comment by jack-watts** [comment]
@Insanitygift 

Coming from D-Cinema, the term Original Version (OV) refers to the first version of a title created for distribution of which all corresponding Supplemental/Version Files will be reliant upon. For D-Cinema an OV is often associated with the Packing List (PKL) in it being a complete/flattened package that acts as the parent to the corresponding child packages which are partial in nature, being supplemental packages (VFs).

Proposed definition:

"Refers to a complete IMP from which other supplemental packages are created." 

In addition, WG proposes the creation of anti-definition section; so as to ensure legacy terms do not influence IMF. [See issue 22.](https://github.com/imfug/002-pkg-and-delivery/issues/22)

**Comment by jack-watts** [comment]
WG proposal 23092020

OV to be moved to anti-definition section

Definition to define the three main uses
1. EIDR L2 
2. D-Cinema
3. Originally created Composition
4. An IMP

Proposed definition;

When used in IMF, the term Original Version (OV) can result in multiple interpretations. 4 of the main interpretations are as follows;
1. An EIDR Level 2 Description
2. A D-Cinema Original Version (i.e the PKL)
3. An originally created IMF composition
4. An originally created IMP

A user should be explicit as to which interpretation represents their intention.

**Comment by jack-watts** [comment]
@Insanitygift Can you please provide feedback on this. Thank you.

**Comment by Insanitygift** [comment]
Hi Jack, are you referring to this?

WG proposal 23092020
OV to be moved to anti-definition section
Definition to define the three main uses

  1.  EIDR L2
  2.  D-Cinema
  3.  Originally created Composition
  4.  An IMP
Proposed definition;
When used in IMF, the term Original Version (OV) can result in multiple interpretations. 4 of the main interpretations are as follows;

  1.  An EIDR Level 2 Description
  2.  A D-Cinema Original Version (i.e the PKL)
  3.  An originally created IMF composition
  4.  An originally created IMP
A user should be explicit as to which interpretation represents their intention.

**Comment by Insanitygift** [comment]
OV to be moved to anti-definition section.   DOES THIS MEAN THERE WILL BE NO "ACTUAL" DEFINITION?

Definition to define the three main uses    THERE ARE FOUR HERE

    EIDR L2    THIS STRICTLY REFERS TO THE ORIGINAL CUT OF THE CONTENT, AND SINCE "VERSION" IS DEFINED AS THE CUT, THEN I AM OK WITH LEAVING THIS EVEN THOUGH IT'S NOT A COMPLETE DEFINITION
    D-Cinema
    Originally created Composition    THIS SAYS LITTLE TO ME. I WOULD PREFER "COMPOSITION REPRESENTING THE CONTENT AS ORIGINALLY CREATED BY THE TALENT"
    An IMP   DOES THIS MEAN "THE FIRST IMF PACKAGE CREATED FOR THE CONTENT?" 

Proposed definition;

When used in IMF, the term Original Version (OV) can result in multiple interpretations. 4 of the main interpretations are as follows;

    An EIDR Level 2 Description
    A D-Cinema Original Version (i.e the PKL)  I THINK THIS LOOSLY MEANS THE DCP CONTAINING THE COMPOSITION THAT REPRESENTS THE CONTENT AS ORIGINALLY CREATED BY THE TALENT, AND IMPLIES THAT OTHER DCP'S CAN BE CREATED LATER THAT ARE OTHER VERSIONS, EITHER USING "VERSION PACKAGES", OR A COMPLETELY NEW DCP.
    An originally created IMF composition    "IMF COMPOSITION REPRESENTING THE CONTENT AS ORIGINALLY CREATED BY THE TALENT"
    An originally created IMP    THIS SAYS LITTLE.  DOES IT MEAN "THE FIRST IMF PACKAGE CREATED FOR THE CONTENT?" I HAVE NO IDEA WHY THAT WOULD NEED TO BE CLASSIFIED UNLESS THAT IMP CONTAINED THE IMF COMPOSITION REPRESENTING THE CONTENT AS ORIGINALLY CREATED BY THE TALENT".  IF ALL IT MEANS IS IT IS THE FIRST IMP CREATED IN A LONG LINE OF OF THEM, WHAT IS UNIQUE OTHER THAN THAT?  MAYBE THIS IS TRYING TO MEAN THE SAME THING FOR IMF THAT "D-CINEMA ORIGINAL VERSION" MEANS FOR DCP?

**Comment by Insanitygift** [comment]
Distilling down the above comments, I would propose:

--An EIDR Level 2 Description that indicates it is the original cut of the content. To be a true original version, it should also have the original spoken language and original subtitles

--A D-Cinema Original Version (i.e the PKL) containing a CPL that plays a composition representing the content as originally created by the talent. This can be used with supplemental packages to create additional versions

--An IMF Composition representing the content as originally created by the talent.

--IMP original version (i.e the PKL) containing a CPL that plays a composition representing the content as originally created by the talent. This can be used with supplemental packages to create additional versions

**Comment by jack-watts** [comment]
WG agreed on 30092020

When used in IMF, the term Original Version (OV) can result in multiple interpretations. 4 of the main interpretations are as follows;

  1. An EIDR Level 2 Description that indicates it is the original cut of the content. To be a true original version, it should also have the original spoken language and original subtitles
  2.  A D-Cinema Original Version (i.e the PKL) containing a CPL that plays a composition representing the content as originally created by the talent. This can be referenced by supplemental packages to create additional versions.
  3.  An IMF Composition representing the content as originally created by the talent.
  4.  An IMP original version (i.e the PKL) containing a CPL that plays a composition representing the content as originally created by the talent. This can be referenced by supplemental packages to create additional versions.

A user should be explicit as to which interpretation represents their intention.
