### ISSUE TITLE
Consolidated Composition - term mismatch

### ISSUE THREAD

**Issue by SteveLLamb** [imfug/002-pkg-and-delivery#59]
"This term is synonymous to flattened composition."

should be updated to:

"This term is synonymous to flattened _package_."

to match the term defined as such.

**Comment by jack-watts** [comment]
This is a typo on my part in porting the word do to HTML. It should be flattened composition, the structure as agreed by the WG. (See issues #16 and #26).

That said, you do highlight the absence of flattened package which is a commonly used term. therefore I propose its inclusion in the anti-definition section with the meaning "This term is synonymous to flattened composition"

My reasoning for it being in the anti-definition section is for the sake of ensuring end users think of the CPL when it comes to track files references through consolidation rather than the PKL.

Thoughts?

**Comment by SteveLLamb** [comment]
So... flattened package in the terms will be updated to flattened composition, and then flattened package will be added to anti-definitions. 

If that is the case, then agreed.

**Comment by jack-watts** [comment]
Yes, that is correct. Flattened Composition is how it was published in the first version https://www.imfug.com/TR/pkg-and-delivery/.

We will just be adding the term flattened package to anti-definitions.

**Comment by gimansour** [comment]
in The Definition section, the term `Consolidated Composition` is defined twice, was that intended?

**Comment by jack-watts** [comment]
No. That is a typo. The first instance should be Consolidation. Hence why Consolidated Composition leads with "A Composition resulting from Consolidation"
